server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router — servir index.html para todas as rotas
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API → backend K8s service
    location /api/ {
        proxy_pass http://nerv-pantry-backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 60s;
        client_max_body_size 15M;
    }
}
