"""add location_id expiry_date barcode to receipt_items

Revision ID: 63b113992af0
Revises: fd6daa5bd10f
Create Date: 2026-06-21 22:20:40.179203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63b113992af0'
down_revision: Union[str, None] = 'fd6daa5bd10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('receipt_items', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('receipt_items', sa.Column('barcode', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'receipt_items', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipt_items', type_='foreignkey')
    op.drop_column('receipt_items', 'barcode')
    op.drop_column('receipt_items', 'expiry_date')
    op.drop_column('receipt_items', 'location_id')
    # ### end Alembic commands ###
