"""add unit_guess is_manual add_to_inventory to receipt_items

Revision ID: fd6daa5bd10f
Revises: e21a6cacfed6
Create Date: 2026-06-20 23:02:01.403791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6daa5bd10f'
down_revision: Union[str, None] = 'e21a6cacfed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('unit_guess', sa.String(length=20), nullable=True))
    op.add_column('receipt_items', sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('receipt_items', sa.Column('add_to_inventory', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_items', 'add_to_inventory')
    op.drop_column('receipt_items', 'is_manual')
    op.drop_column('receipt_items', 'unit_guess')
    # ### end Alembic commands ###
